// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbtypes

import (
	"context"
)

type Querier interface {
	// ============================================================================
	// Existence Check Queries
	// ============================================================================
	GameExist(ctx context.Context, id int32) (int64, error)
	// ============================================================================
	// Basic Retrieval Queries
	// ============================================================================
	GetAllGames(ctx context.Context) ([]Game, error)
	// ============================================================================
	// Match Selection Queries (for Calendar Export)
	// ============================================================================
	GetCalendarMatchesBySelections(ctx context.Context, arg GetCalendarMatchesBySelectionsParams) ([]GetCalendarMatchesBySelectionsRow, error)
	// ============================================================================
	// Match Selection Queries (for Preview)
	// ============================================================================
	GetFutureMatchesBySelections(ctx context.Context, arg GetFutureMatchesBySelectionsParams) ([]GetFutureMatchesBySelectionsRow, error)
	GetLeaguesByGameID(ctx context.Context, gameID int32) ([]GetLeaguesByGameIDRow, error)
	// ============================================================================
	// Live Matches Queries
	// ============================================================================
	GetLiveMatches(ctx context.Context) ([]GetLiveMatchesRow, error)
	// ============================================================================
	// Single-match lookup (used by prediction handlers)
	// ============================================================================
	GetMatchByID(ctx context.Context, id int32) (GetMatchByIDRow, error)
	GetMatchesInRangeBySelections(ctx context.Context, arg GetMatchesInRangeBySelectionsParams) ([]GetMatchesInRangeBySelectionsRow, error)
	GetOngoingMatchesBySelections(ctx context.Context, arg GetOngoingMatchesBySelectionsParams) ([]GetOngoingMatchesBySelectionsRow, error)
	GetPastMatchesBySelections(ctx context.Context, arg GetPastMatchesBySelectionsParams) ([]GetPastMatchesBySelectionsRow, error)
	GetSeriesByGameID(ctx context.Context, gameID int32) ([]Series, error)
	GetTeamsByGameID(ctx context.Context, gameID int32) ([]Team, error)
	GetURLMapping(ctx context.Context, hashedKey string) (UrlMapping, error)
	// ============================================================================
	// INSERT/UPSERT Queries
	// ============================================================================
	InsertToGames(ctx context.Context, arg InsertToGamesParams) error
	InsertToLeagues(ctx context.Context, arg InsertToLeaguesParams) error
	InsertToMatches(ctx context.Context, arg InsertToMatchesParams) error
	InsertToSeries(ctx context.Context, arg InsertToSeriesParams) error
	InsertToTeams(ctx context.Context, arg InsertToTeamsParams) error
	InsertToTournaments(ctx context.Context, arg InsertToTournamentsParams) error
	// ============================================================================
	// URL Mapping Queries (for Calendar Links)
	// ============================================================================
	InsertURLMapping(ctx context.Context, arg InsertURLMappingParams) error
	LeagueExist(ctx context.Context, id int32) (int64, error)
	// ============================================================================
	// Maintenance Queries
	// ============================================================================
	MarkPastUnfinishedMatchesAsFinished(ctx context.Context) error
	MatchExist(ctx context.Context, id int32) (int64, error)
	SeriesExist(ctx context.Context, id int32) (int64, error)
	TeamExist(ctx context.Context, id int32) (int64, error)
	TournamentExist(ctx context.Context, id int32) (int64, error)
	UpdateURLMappingAccessCount(ctx context.Context, hashedKey string) error
}

var _ Querier = (*Queries)(nil)
