// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AboutPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto p-4\"><div class=\"max-w-4xl mx-auto\"><div class=\"card bg-base-100 shadow-xl\"><div class=\"card-body\"><h1 class=\"card-title text-3xl mb-6\">About EsportsCalendar</h1><!-- What is this --><section class=\"mb-8\"><h2 class=\"text-2xl font-bold mb-3\">What is EsportsCalendar?</h2><p class=\"text-base-content/80 leading-relaxed\">EsportsCalendar is a free tool that helps esports fans track upcoming matches across multiple games and leagues. Simply select your favorite games, teams, and leagues, and export a personalized calendar that syncs with your favorite calendar app (Google Calendar, Apple Calendar, Outlook, etc.).</p></section><!-- Features --><section class=\"mb-8\"><h2 class=\"text-2xl font-bold mb-3\">Features</h2><ul class=\"list-disc list-inside space-y-2 text-base-content/80\"><li>Support for multiple popular esports titles</li><li>Filter by specific leagues, teams, and tournament tiers</li><li>Automatic timezone conversion to your local time</li><li>Standard .ics calendar format for universal compatibility</li><li>Dark mode support for comfortable viewing</li><li>No account required - completely free to use</li></ul></section><!-- Data Source --><section class=\"mb-8\"><h2 class=\"text-2xl font-bold mb-3\">Data Source</h2><p class=\"text-base-content/80 leading-relaxed mb-2\">Match data is sourced from PandaScore API, which provides comprehensive coverage of esports tournaments and matches. The calendar automatically updates to reflect the latest schedule information.</p><div class=\"alert alert-info\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = IconInfo("stroke-current shrink-0 w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span>Once you export your calendar, it will automatically refresh with new matches and updates.</span></div></section><!-- How It Works --><section class=\"mb-8\"><h2 class=\"text-2xl font-bold mb-3\">How It Works</h2><div class=\"steps steps-vertical lg:steps-horizontal\"><div class=\"step step-primary\"><div class=\"text-left ml-4\"><p class=\"font-semibold\">Select Games</p><p class=\"text-sm text-base-content/60\">Choose which esports you want to follow</p></div></div><div class=\"step step-primary\"><div class=\"text-left ml-4\"><p class=\"font-semibold\">Pick Teams & Leagues</p><p class=\"text-sm text-base-content/60\">Filter by your favorite teams and leagues</p></div></div><div class=\"step step-primary\"><div class=\"text-left ml-4\"><p class=\"font-semibold\">Export Calendar</p><p class=\"text-sm text-base-content/60\">Get a link to add to your calendar app</p></div></div></div></section><!-- Open Source --><section class=\"mb-8\"><h2 class=\"text-2xl font-bold mb-3\">Open Source</h2><p class=\"text-base-content/80 leading-relaxed mb-4\">EsportsCalendar is open source and built with modern technologies including Go, templ, HTMX, and DaisyUI. Contributions, bug reports, and feature requests are welcome on GitHub.</p><div class=\"flex gap-3\"><a href=\"https://github.com/feimaomiao/esportscalendar\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"btn btn-primary\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = IconGitHub("w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "View on GitHub</a> <a href=\"https://github.com/feimaomiao/esportscalendar/issues\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"btn btn-outline\">Report an Issue</a></div></section><!-- Support --><section class=\"mb-4\"><h2 class=\"text-2xl font-bold mb-3\">Support the Project</h2><p class=\"text-base-content/80 leading-relaxed mb-4\">EsportsCalendar is free to use and will always be free. If you find it useful, consider supporting the project to help cover server costs and ongoing development.</p><a href=\"https://www.buymeacoffee.com/feimaomiao\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"btn btn-accent\">☕ Buy Me a Coffee</a></section><!-- Back Button --><div class=\"card-actions justify-start mt-8\"><a href=\"/\" class=\"btn btn-ghost\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = IconArrowLeft("w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "Back to Home</a></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = BaseLayout("About - EsportsCalendar").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
