// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HowToUsePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto p-4\"><div class=\"max-w-4xl mx-auto\"><div class=\"card bg-base-100 border border-base-300\"><div class=\"card-body\"><div class=\"flex items-baseline justify-between mb-1\"><span class=\"hud-label\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("// manual")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/how-to-use.templ`, Line: 10, Col: 44}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span> <span class=\"hud-label hud-bracket\">how to use</span></div><h1 class=\"hud-display text-3xl mb-4\">Operations</h1><p class=\"hud-mono text-sm opacity-60 mb-6\">Generate a personalized calendar feed and subscribe to it in your calendar app.</p><div class=\"space-y-6\"><!-- Step 1 --><div class=\"hud-game-module\"><div class=\"hud-game-module-head\"><span class=\"hud-step-num\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("[ 01 ]")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/how-to-use.templ`, Line: 21, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span><h2 class=\"hud-display text-lg\">Select Games</h2></div><div class=\"hud-game-module-body\"><p>Choose which games to track. You can pick one or many.</p><div class=\"hud-alert hud-alert-info mt-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = IconInfo("stroke-current shrink-0 w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<span>Select only the games you actively follow to keep your calendar focused.</span></div></div></div><!-- Step 2 --><div class=\"hud-game-module\"><div class=\"hud-game-module-head\"><span class=\"hud-step-num\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs("[ 02 ]")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/how-to-use.templ`, Line: 37, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span><h2 class=\"hud-display text-lg\">Choose Leagues &amp; Teams</h2></div><div class=\"hud-game-module-body\"><p>For each game, pick which leagues and teams to follow. Filter by tournament tier to exclude lower-stakes matches.</p><ul class=\"mt-3 space-y-2\"><li class=\"flex items-start gap-3\"><span class=\"hud-mono text-primary text-xs mt-1\">›</span><div><strong class=\"hud-mono uppercase tracking-wider text-sm\">Search Leagues</strong> — find specific leagues to track</div></li><li class=\"flex items-start gap-3\"><span class=\"hud-mono text-primary text-xs mt-1\">›</span><div><strong class=\"hud-mono uppercase tracking-wider text-sm\">Search Teams</strong> — follow your favorite teams across all tournaments</div></li><li class=\"flex items-start gap-3\"><span class=\"hud-mono text-primary text-xs mt-1\">›</span><div><strong class=\"hud-mono uppercase tracking-wider text-sm\">Tier Filter</strong> — Tier S is highest, \"All\" includes everything</div></li></ul></div></div><!-- Step 3 --><div class=\"hud-game-module\"><div class=\"hud-game-module-head\"><span class=\"hud-step-num\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs("[ 03 ]")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/how-to-use.templ`, Line: 63, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span><h2 class=\"hud-display text-lg\">Preview &amp; Export</h2></div><div class=\"hud-game-module-body\"><p>Preview the matches that will appear in your feed. If they look right, hit Export to generate your calendar URL.</p><div class=\"hud-alert hud-alert-success mt-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = IconCheckCircle("stroke-current shrink-0 w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<span>The preview shows upcoming matches. Your calendar updates automatically as new matches are scheduled.</span></div></div></div><!-- Step 4 --><div class=\"hud-game-module\"><div class=\"hud-game-module-head\"><span class=\"hud-step-num\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs("[ 04 ]")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/how-to-use.templ`, Line: 79, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span><h2 class=\"hud-display text-lg\">Subscribe to Calendar</h2></div><div class=\"hud-game-module-body\"><p class=\"mb-4\">After generating your feed URL, subscribe to it in your calendar app. This creates a live feed that auto-updates.</p><label class=\"hud-collapse\"><input type=\"checkbox\"> <span class=\"hud-collapse-title\">Apple Calendar (macOS / iOS)</span><div class=\"hud-collapse-content\"><ol class=\"list-decimal list-inside space-y-2 mt-2 text-sm\"><li>Copy the generated calendar link</li><li>Open Calendar app</li><li>Go to <strong>File → New Calendar Subscription</strong> (macOS) or <strong>Settings → Accounts → Add Account → Other → Add Subscribed Calendar</strong> (iOS)</li><li>Paste the calendar URL</li><li>Click Subscribe and customize the name/color if desired</li></ol></div></label> <label class=\"hud-collapse\"><input type=\"checkbox\"> <span class=\"hud-collapse-title\">Google Calendar</span><div class=\"hud-collapse-content\"><ol class=\"list-decimal list-inside space-y-2 mt-2 text-sm\"><li>Copy the generated calendar link</li><li>Open Google Calendar on web</li><li>Click the <strong>+</strong> next to \"Other calendars\"</li><li>Select <strong>\"From URL\"</strong></li><li>Paste the calendar URL</li><li>Click <strong>Add calendar</strong></li></ol></div></label> <label class=\"hud-collapse\"><input type=\"checkbox\"> <span class=\"hud-collapse-title\">Outlook</span><div class=\"hud-collapse-content\"><ol class=\"list-decimal list-inside space-y-2 mt-2 text-sm\"><li>Copy the generated calendar link</li><li>Open Outlook Calendar</li><li>Go to <strong>Add Calendar → Subscribe from web</strong></li><li>Paste the calendar URL</li><li>Name your calendar and click <strong>Import</strong></li></ol></div></label></div></div><!-- Additional Info --><div class=\"hud-game-module\"><div class=\"hud-game-module-head\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = IconInfo("h-5 w-5 stroke-current text-primary").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<h2 class=\"hud-display text-lg\">Notes</h2></div><div class=\"hud-game-module-body\"><div class=\"space-y-2 text-sm\"><p><strong class=\"hud-mono uppercase tracking-wider text-xs\">Time Zone:</strong> Match times are stored in UTC. Your calendar app converts them to your local timezone automatically.</p><p><strong class=\"hud-mono uppercase tracking-wider text-xs\">Updates:</strong> The feed auto-updates. Calendar apps may take a few hours to a day to sync, depending on settings.</p><p><strong class=\"hud-mono uppercase tracking-wider text-xs\">Multiple Games:</strong> Multiple games are bundled into a single calendar feed.</p></div></div></div><div class=\"card-actions justify-center mt-2\"><a href=\"/\" class=\"btn btn-primary btn-lg\">&gt; Get Started")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = IconArrowRight("w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</a></div></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = BaseLayout("How to Use - EsportsCalendar").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
